### ISSUE TITLE
Legend displays incorrectly on smaller screen

### ISSUE THREAD

**Issue by aleathwick** [UoA-eResearch/deckly#2]
For viewport of 1536x722 (on my laptop screen), the legend displays as seen in attached screenshot. Displays fine on a larger monitor.
![image](https://user-images.githubusercontent.com/49058587/105095133-2ac0a180-5b0a-11eb-89e9-74f02eee0483.png)

**Comment by neon-ninja** [comment]
Thanks for the bug report. Issue was also occurring with browser zoom in a 1920x1080 viewport. This commit https://github.com/UoA-eResearch/deckly/commit/ec6299f2824c046ec5f7ea8b2e21425ea4866cca should fix the issue, which I've just published as version 1.0.7 on NPM

**Comment by aleathwick** [comment]
Thank you!

**Comment by aleathwick** [comment]
Similar issue still exists for univariate legends

**Comment by neon-ninja** [comment]
This commit should fix the problem for univariate legends - https://github.com/UoA-eResearch/deckly/commit/11646d76f2511887aced632b16f3d6b81c42ae6b
Published as version 1.0.11

**Comment by aleathwick** [comment]
All fixed now
